### ISSUE TITLE
Allow automatic triggering of autofixing of Pull Request linting errors with a comment

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10876]
## Expected behavior
A Github action that is triggered by comments on open Pull Requests.

If the pull request comment contains the text "autofixme!" then the workflow should run `pre-commit run --all-files` or equivalent on the code of the pull request. If there are any unstaged changes after this (i.e. autofixes have been generated), then they should be committed and pushed to the pull request branch.

This may be most easily accomplished by simply triggering the pre-commit-ci lite action in the case that autofixme! is detected https://pre-commit.ci/lite.html

**Comment by im-NL** [comment]
I've spent too many hours and this script detects the comment but the workflow seems to be skipping the `pre-commit-ci/lite-action@v1.0.1` step every time after the previous step exits with this error -> https://pastebin.com/XcNBmTKx
```
name: autofix linting errors
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  autofix:
    if: contains(github.event.comment.body, 'autofixme!')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
```
I feel like pre-commit.ci doesn't work well with comments. It would be simpler to just run a lint check on every pull request as shown in the docs

**Comment by MisRob** [comment]
Thank you for looking into this @im-NL. @rtibbles has a good experience with GH actions - any recommendations on how to proceed?

**Comment by rtibbles** [comment]
The error there seems to be coming from the incorrect version of node being used. If you look at our current pre-commit action: https://github.com/learningequality/kolibri/blob/develop/.github/workflows/pre-commit.yml#L36 the version of node needs to be properly set.

The reason that pre-commit-ci/lite-action is not doing anything is because there is nothing to commit. The error is coming from the incorrect node version, not any linting failure.

**Comment by im-NL** [comment]
Yes thank you @rtibbles, I hadn't been reading the error message properly before.

When pre-commit-ci lite is triggered by comments, it says `skip: not a pull request`. It looks like autofixing doesn't work in this case (?)
This is the autofix file
```
name: autofix linting errors
on:
  issue_comment:
    types: [created]
jobs:
  autofix:
    if: contains(github.event.comment.body, 'autofixme!')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          npm rebuild node-sass

      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
```
Instead, should we just run pre-commit-ci lite on every pull request? That would be a very simple fix
