### ISSUE TITLE
Kolibri is slow for Nalanda's use case

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#1887]
This is a catch-all issue for the performance problems encountered by Nalanda. I'll be putting my investigations here over the coming days.

PRs created to address the performance issues:

- Separate session DB: https://github.com/learningequality/kolibri/pull/1883
- PRAGMAs: https://github.com/learningequality/kolibri/pull/1885

Ideas for tools:
- find the inflection point in the # of users, when our performance degrades
- measure CPU, memory, network and disk utilization during a set amount of time

**Comment by aronasorman** [comment]
I've made a short load testing script using artillery.io:

```
config:
  target: "http://10.0.0.27:8080"
  phases:
    - duration: 10
      arrivalRate: 5
#    - duration: 30
#      arrivalRate: 20
  processor: "./utils.js"
scenarios:
  - name: "Log in and learn"
    flow:
      - function: "generateRandomUserData"
      - post:
          url: /api/signup/
          json:
            facility: 7de938b6b5ae696d521926e764858120
            full_name: "{{ fullname }}"
            password: "{{ password }}"
            username: "{{ username }}"
      - get:
          url: /learn/#/1d8f6d84618153c18c695d85074952a7/
```

Hacky, but it got us results. This is using the Nalanda laptop we got in the office a while back: https://gist.github.com/aronasorman/47217abcf52a6f7b548b9b98ae5f4fe7

Separate session DBs are the most promising so far. But, I am not satisfied with our methodology so far, which involves guessing what will work and then testing it. I'm going to see what resources are being saturated exactly, and then go from there.
