### ISSUE TITLE
ios momentum scrolling not working

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2279]
report: no momentum scrolling on mobile. Chrome app, iPhone 6, iOS 10.3.3

**Comment by HansGam** [comment]
.

**Comment by jonboiser** [comment]
We reopened this because the `-webkit-overflow-scrolling :touch` rule interacts with the "scrolling pane" CSS or code to make the App Bar unusable on iOS, so it was removed in #5100.

**Comment by indirectlylit** [comment]
from https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

```css
.class {
  overflow-y: scroll; /* has to be scroll, not auto */
  -webkit-overflow-scrolling: touch;
}
```
